id: P45C5B5C0
initial_creation_type: input
source_metadata:
  title: Jamyang Khyentse Wangpo Series
  language: it
  description: 'Texts by and about the great Rimé (“nonsectarian”) master Jamyang
    Khyentse Wangpo (''jam dbyangs mkhyen brtse''i dbang po, 1820–1892), one of the
    most influential figures of recent times:'
  volume:
    d0b1bc8847fa4369b2126748e80b1410:
      title: 'A Few Words of Commentary to Clarify The Essence of Nectar: Graduated
        Stages of the Path—Advice for Renunciant Meditators'
      parent: Advice
    727011a2c9fd4384ba750c75a2597643:
      title: 'The Essence of Nectar: Graduated Stages of the Path — Advice for Renunciant
        Meditators'
      parent: Advice
    2b0607535f2941f887a1908aee166668:
      title: Biography of Jamyang Khyentse Wangpo
      parent: Biography
    f8fc5d61acb84bcbbfa835900f3c2b8d:
      title: The Life of Jamyang Khyentse Wangpo
      parent: Biography
    70ca8e1879d14ddabefe4f2d569c1b8c:
      title: 'The Seed of Reasoning: Notes on the Five Great Logical Arguments of
        the Middle Way'
      parent: Buddhist Philosophy
    3c4def2c06d944d693fe425ffef46fd6:
      title: 'A Few Remarks: An Explanation of the Praise to Noble Mañjuśrī known
        as Glorious Wisdom’s Excellent Qualities'
      parent: Commentaries
    ca1c9c170e214cfabbb694c29fc43cd5:
      title: Guide to the Practice of Narak Kong Shak
      parent: Confession
    7d14d303db784304b35b586bb2639ddd:
      title: 'The Rain of Virtue and Goodness: A Short Practice for Consecrating Representations
        of Enlightened Body, Speech and Mind'
      parent: Consecration
    76cd85f5e30f4853be29fedae6841f98:
      title: 'The Vajra Lute: A Brief Fulfilment for the Guru Practice of Vidyādhara-Assembly'
      parent: Fulfilment
    9e96dff01e9e4ab080b5cc6866df6bde:
      title: 'A Shortcut to the Siddhi of Immortality: Guru Yoga of Union with the
        Three Deities of Long Life'
      parent: Guru Yoga
    06b03db24b02484da6415cf12378ae40:
      title: A Brief History of the Sacred Image of White Tārā
      parent: History
    c1d991b76c044815b0bfec19a84865c6:
      title: The History of the Hearing Lineage of the Profound and Secret Practice
        of Siṃhamukhā
      parent: History
    c53e576e87494e09a4147090b61bbda4:
      title: 'A Shower of Great Bliss: A Lineage Prayer for the Guru Yoga based on
        Vajrasattva'
      parent: Lineage Prayers
    91f94b9c66394b70811e40a433958358:
      title: 'Bestower of the Light of Intelligence: A Prayer to the Lineage of the
        Profound Sādhana Based Upon the Praise to Venerable Mañjughoṣa'
      parent: Lineage Prayers
    1ab3559716014d50988340f7454645ba:
      title: 'Source of Magnificent Blessing: A Prayer to the Lineage of the Secret
        Practice of the Great Compassionate One, Natural Liberation of Suffering'
      parent: Lineage Prayers
    16bbc8244dc44f358cf21f8ea6ac1129:
      title: Supplement to the Omniscient Ngorchen Kunga Zangpo’s Prayer to the Lineage
        of Parting from the Four Attachments
      parent: Lineage Prayers
    759483439246443abc0ab2ba7f38519f:
      title: 'The Flower of Faith: A Prayer to the Twenty-Five Founders of Buddha''s
        Teachings in Tibet'
      parent: Lineage Prayers
    254f2b3a15364e0582effc6f75112228:
      title: 'The Garland of Utpala Flowers: A Prayer to the Masters of the Lineage
        of Zabtik Drolchok'
      parent: Lineage Prayers
    f4f92f663d9d48d0aa8cd2a40efd4653:
      title: 'The Seed of Faith: A Prayer to the Sublime Ones'
      parent: Lineage Prayers
    120544c4a5fd419bb999946f8df46ac6:
      title: 'The Shower of Great Bliss: A Prayer to the Lineage of the Female Awareness-Holder
        (Yumka)'
      parent: Lineage Prayers
    77778e1be5ad41028e11ee7b88fcacc6:
      title: Ambrosia for the Mind
      parent: Lojong
    2a4ebcabddd044c39bed5b7675bc8ff6:
      title: 'Nectar of the Heart: An Experiential Song of Parting from the Four Attachments'
      parent: Lojong
    22701910afe2460fb2da905a68bf1d53:
      title: 'Words of Advice on Accomplishing Immortality: An Extremely Concise Daily
        Practice Uniting the Short Lineages of Amitāyus and Hayagrīva'
      parent: Longevity
    514ff9ae0e5e4ec58862043436465152:
      title: 'Wisdom''s Bestowal: A Way to Accumulate the Recitation of the Tantra
        ''Chanting the Names of Mañjuśrī'' (Mañjuśrī Nāma Saṃgīti)'
      parent: Mañjuśrī
    6fc697575a9243d9bc9b7a24c56425f4:
      title: 'A Profound Concentration of Nectar: Essentialized Stages of Visualization
        for the Preliminary Practices of the Heart Essence of the Vast Expanse (Longchen
        Nyingtik)'
      parent: Ngöndro
    672db843d97b4b908b030ea0d4d15829:
      title: 'Illuminating the Excellent Path to Omniscience: Notes on the Longchen
        Nyingtik Ngöndro'
      parent: Ngöndro
    c39ebcba8ecd41e191c06cc4fc6e24d4:
      title: 'The Excellent Path to Enlightenment: A Brief Practice of the Preliminaries'
      parent: Ngöndro
    e8e84b0d8b5142918fa8601297dba300:
      title: A Brief Practice of Consecrating Amṛta for the Vidyādhara Assembly
      parent: Offering
    ec75d7f24bd04c6a8a088259ee2281fc:
      title: Concise Seven-Heap Maṇḍala Offering
      parent: Offering
    0a62f02a0125459a9d2d18275ed9f7ce:
      title: Offering the Eight Auspicious Substances and Seven Emblems of Royalty
      parent: Offering
    4ca045e190f1428c81cac333f4eac9d2:
      title: Short Maṇḍala Offering
      parent: Offering
    73b397ee0ece41cfa6bd0d1a17b9c690:
      title: 'The Offering Clouds of the Indestructible Ladies of Sound: Concise Garland
        of Offerings of the Sixteen Vajra Goddesses'
      parent: Offering
    29d6767edbb74e9c8015ae9baf7fb3e6:
      title: In Praise of Jamyang Khyentse Wangpo
      parent: Praise
    fcb940df09b041d7838b316ff2bd0f73:
      title: 'Music to Delight the Ḍākinī: A Praise to the Deathless Mandāravā'
      parent: Praise
    5c47bd869eeb46859b2a1e9648452962:
      title: A Short Prayer Based on the Life and Liberation of the All-Knowing, All-Seeing
        Jamyang Khyentse Wangpo
      parent: Prayers
    965b0c984fee4ca882cd0f6432674575:
      title: Prayer to Chökyi Wangpo, the Bodhisattva and Tamer of Beings
      parent: Prayers
    0ea0a490fb8b43c68327dbcf9d6f7e89:
      title: Prayer to Jamyang Khyentse Wangpo
      parent: Prayers
    8f2ebc88d3b04c9cb0c0f7b1b894dae1:
      title: Prayer to Jamyang Khyentse Wangpo and Jamyang Khyentse Chökyi Lodrö
      parent: Prayers
    bf2cf7cb65324b34834b409b2d88f137:
      title: Prayer to Jamyang Khyentse Wangpo, Jamgön Kongtrul and Jamyang Khyentse
        Chökyi Lodrö
      parent: Prayers
    e4752b262d9e45f280ba2374831a0aba:
      title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
      parent: Prayers
    5686dfc6be3c447ea6f764d3ef590cf8:
      title: Prayer to Root and Lineage Masters, and the Assembly of Deity, Ḍākinīs
        and Dharma Protectors of the Sakya Lineage
      parent: Prayers
    3de6278d79204a38ab02bca84b4414d0:
      title: Prayer to Thangtong Gyalpo
      parent: Prayers
    b8faba7d18e44ebc9a4e252804660af4:
      title: Prayer to the Siddha Virūpa
      parent: Prayers
    8106b976c9fd4cbfbc120f87d663d278:
      title: Supplication to Lord Buddha together with the Sixteen Arhats
      parent: Prayers
    b930698149a341d991f7b3e3c35ea5b7:
      title: 'The Melodious Sound of Gathering Auspiciousness: A Prayer Based on the
        Liberational Life of the Omniscient Jamyang Khyentse Wangpo'
      parent: Prayers
    940aeefcd9fd4293bd14dd21a6f54f34:
      title: 'The Melody of Complete Accomplishment: A Prayer to Those Praised as
        Ornaments of the Practice Lineage'
      parent: Prayers
    b9c579ea460043829c4810ff204f2a0f:
      title: 'The Sweet-Sounding Song that Fulfils All Aims: A Prayer to Noble Tārā
        Combined with Her Root Mantra'
      parent: Prayers
    82024ed252de46738b3bd5ede6e7cbce:
      title: Words of Jamyang Khyentse
      parent: Prayers
    b2d3ed3f3eda4958b4e1f23fbf9b4e28:
      title: 'A Beautiful and Wondrous Udumbara Garland: A Supplication and Summary
        of the Chronicles of Padma, The Life and Liberation of the Precious Guru of
        Uḍḍiyāna'
      parent: Prayers to Guru Rinpoche
    8720931bcb8847e4bdd834751dbb384b:
      title: A Brief Prayer to the Precious Master Padmākara for Swiftly Fulfilling
        Wishes
      parent: Prayers to Guru Rinpoche
    136a8f68f21543af84458edf64dc6f46:
      title: 'The Chariot of the Vidyādharas: An Aspiration Prayer for Travelling
        to the Realm of Lotus Light'
      parent: Prayers to Guru Rinpoche
    2f0d6fccd61d4eeaa8326f3c7e538d40:
      title: The General Visualization for Prayers to Guru Rinpoche
      parent: Prayers to Guru Rinpoche
    a6628e50698a4db6bfd8af1191276593:
      title: 'The Heart of Blessings: A Brief Anthology of Prayers to Guru Rinpoche
        and the Twenty-Five Disciples, the King and Subjects'
      parent: Prayers to Guru Rinpoche
    c6f16b8c7498452faf6ec8f6becae1a0:
      title: 'Turning Back Obstacles and Adverse Circumstances: A Prayer to Orgyen
        Rinpoche, Embodiment of All Sources of Refuge'
      parent: Prayers to Guru Rinpoche
    59a39df04a4c4eb4b3ec345814f4dfab:
      title: 'Wish-Fulfilling Feast of Siddhis: An Aspiration Prayer to Orgyen Rinpoche,
        the Precious Master of Oddiyana'
      parent: Prayers to Guru Rinpoche
    f31af726ab9546299441124257e48ff5:
      title: A Brief Practice of Paying Homage and Making Offerings to the Sixteen
        Elders
      parent: Sādhanas
    bfcfbcd84a1544149d912f400ab076e5:
      title: Activities for Uncovering Primordial Wisdom from the Chimé Pakmé Nyingtik,
        ‘The Heart Essence of the Sublime Lady of Immortality’
      parent: Sādhanas
    7f3989efe6154381bed19a18fd639e3f:
      title: 'Fast Track to Happiness and Peace: A Very Brief Meditation and Recitation
        of the Medicine Buddha'
      parent: Sādhanas
    bd8c73c5d57e449496f3d693d3c37493:
      title: 'Moonlight of Pacifying Amṛta: A Daily Visualization and Recitation for
        the Dispeller of All Samaya Corruptions and Pollutions'
      parent: Sādhanas
    bad59a3f58e645a68adf28a3a0f995b1:
      title: The Essential Activity Manual for the Awesome Ones’ Assembly, the Heart
        Practice of Vidyādharas, from the Heart Essence of the Vast Expanse
      parent: Sādhanas
    937145b0edf64c72a674c2aef8ebe5ea:
      title: 'The Heart of Wish-Fulfilling Jewels: A Brief Practice for Paying Homage
        and Making Offerings to the Buddha together with his retinue of Arhats'
      parent: Sādhanas
    aff4e7c36efe415da13769cf7b5a9e44:
      title: 'The Single Mudrā: A Daily Practice for the Awesome Ones’ Assembly (Palchen
        Düpa), the Heart Practice of the Awareness-Holders'
      parent: Sādhanas
    51200f5cf9854709adb6a2febc212a2c:
      title: The Single-Form Daily Practice from Chimé Pakmé Nyingtik (The Heart Essence
        of the Sublime Lady of Immortality)
      parent: Sādhanas
    8fad14f0a7994fae9de8a137ddba0b03:
      title: The Visualization of the Four Goddesses of the Great Compassionate One,
        Natural Liberation of Suffering
      parent: Sādhanas
    3350877adcb0486fa34dbc0a548a5a34:
      title: 'Increasing Life and Vitality: A Practice for Freeing Lives'
      parent: Saving Lives
    4efedb8f2ed44a67a44e109ea7b6c504:
      title: A Section of the Vajrakīla Root Tantra
      parent: Tantra
    2b29c29bbf18499db10b78a0f6fb03fa:
      title: The Twenty-Eight Commitments
      parent: Tantra
    802bccc845d04b89ada70cc8b6875dfd:
      title: 'A Glorious Garland of the Two Accomplishments: An Abridged Feast-Offering
        for the Female Practice of the Ḍākinī'
      parent: Tsok
    0de1fc565a384bbcb1b4702bc4e04ece:
      title: 'Essence of Accomplishment: A Concise Feast-Offering to Noble Tārā'
      parent: Tsok
    8b88f9cbf3874f97958e5baeffaca19c:
      title: 'Harmonious Clouds of Sublime and Lasting Bliss: A Vajra Song for the
        Tsok Feast Offering to Venerable and Exalted Vajrayoginī'
      parent: Tsok
    18ac609331034594a2bef449697e2203:
      title: Short Tsok Offering to the Powerful Lady Kurukullā
      parent: Tsok
    ca7743edd8654f61919c3c5211ab7246:
      title: 'Song and Dance to Delight the Ḍākas and Ḍākinīs: An Aspiration for the
        Sixfold Satisfaction of the Maṇḍala of the Feast-Gathering'
      parent: Tsok
created_at: '2022-02-28T23:57:51.902684'
last_modified_at: '2022-02-28T23:57:51.902687'
